// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9Tl7OXKpnZXBDvxZnhWurXS1gxN_WdmE',
    appId: '1:528775619459:web:c0bf9236ea0f828d6c0cb6',
    messagingSenderId: '528775619459',
    projectId: 'bizhisab-ai-971a9',
    authDomain: 'bizhisab-ai-971a9.firebaseapp.com',
    storageBucket: 'bizhisab-ai-971a9.firebasestorage.app',
    measurementId: 'G-2NG9650M7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqMK4ez9vN53WjOYnMdJDjZFc6jmSRqFQ',
    appId: '1:528775619459:android:b42cea519a4800b66c0cb6',
    messagingSenderId: '528775619459',
    projectId: 'bizhisab-ai-971a9',
    storageBucket: 'bizhisab-ai-971a9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0AfQ4YNzHon_ZUJwBzmHsjk909_criiU',
    appId: '1:528775619459:ios:a6ea9b28e6540f776c0cb6',
    messagingSenderId: '528775619459',
    projectId: 'bizhisab-ai-971a9',
    storageBucket: 'bizhisab-ai-971a9.firebasestorage.app',
    iosBundleId: 'com.example.bizhisabAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9Tl7OXKpnZXBDvxZnhWurXS1gxN_WdmE',
    appId: '1:528775619459:web:688cda47733da4b76c0cb6',
    messagingSenderId: '528775619459',
    projectId: 'bizhisab-ai-971a9',
    authDomain: 'bizhisab-ai-971a9.firebaseapp.com',
    storageBucket: 'bizhisab-ai-971a9.firebasestorage.app',
    measurementId: 'G-4D9VWJREVF',
  );
}
